# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(),
        ),
    ]
