# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160614_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(choices=[('Nrb', 'Nairobi'), ('Nku', 'Nakuru'), ('Mbs', 'Mombasa'), ('Ksm', 'Kisumu'), ('Thk', 'Thika'), ('Nyr', 'Nyeri')], max_length=100, verbose_name='Area of Residence'),
        ),
    ]
