# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160614_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='edu',
            field=models.CharField(choices=[('DP', 'Diploma'), ('Bsc', "Bachelor's Degree"), ('Msc', "Master's Degree"), ('Phd', 'Post Graduate')], default='DP', max_length=50, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='industry',
            field=models.CharField(choices=[('IT', 'IT'), ('CL', 'Cloud'), ('WD', 'Web Development'), ('MO', 'Mobile Development'), ('DE', 'Desktop Development'), ('DV', 'DevOps')], default='IT', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(choices=[('Nrb', 'Nairobi'), ('Nku', 'Nakuru'), ('Mbs', 'Mombasa'), ('Ksm', 'Kisumu'), ('Thk', 'Thika'), ('Nyr', 'Nyeri')], default='Nrb', max_length=100, verbose_name='Area of Residence'),
        ),
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together=set([('name', 'level')]),
        ),
    ]
