# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 14, 19, 14, 18, 543090)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='edu',
            field=models.CharField(choices=[('DP', 'Diploma'), ('Bsc', "Bachelor's Degree"), ('Msc', "Master's Degree"), ('Phd', 'Post Graduate')], default='Bsc', max_length=50, verbose_name='Minimum Education Level'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='industry',
            field=models.CharField(choices=[('IT', 'IT'), ('CL', 'Cloud'), ('WD', 'Web Development'), ('MO', 'Mobile Development'), ('DE', 'Desktop Development'), ('DV', 'DevOps')], default='IT', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='location',
            field=models.CharField(choices=[('Nrb', 'Nairobi'), ('Nku', 'Nakuru'), ('Mbs', 'Mombasa'), ('Ksm', 'Kisumu'), ('Thk', 'Thika'), ('Nyr', 'Nyeri')], default='Nrb', max_length=100),
        ),
    ]
