# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0002_auto_20160614_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='experience',
            field=models.IntegerField(verbose_name='Minimum Experience'),
        ),
    ]
