# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0003_auto_20160614_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobprofile',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='max_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Age'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='min_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Age'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='edu',
            field=models.CharField(choices=[('Bsc', "Bachelor's Degree"), ('DP', 'Diploma'), ('Msc', "Master's Degree"), ('Phd', 'Post Graduate')], default='Bsc', max_length=50, verbose_name='Minimum Education Level'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='gender',
            field=models.CharField(choices=[('FH', 'Female - High'), ('FL', 'Female - Low'), ('FM', 'Female - Medium'), ('MH', 'Male - High'), ('ML', 'Male - Low'), ('MM', 'Male - Medium')], default='FH', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='industry',
            field=models.CharField(choices=[('CLH', 'Cloud - High'), ('CLL', 'Cloud - Low'), ('CLM', 'Cloud - Medium'), ('DEH', 'Desktop Development - High'), ('DEL', 'Desktop Development - Low'), ('DEM', 'Desktop Development - Medium'), ('DVH', 'DevOps - High'), ('DVL', 'DevOps - Low'), ('DVM', 'DevOps - Medium'), ('ITH', 'IT - High'), ('ITL', 'IT - Low'), ('ITM', 'IT - Medium'), ('MOH', 'Mobile Development - High'), ('MOL', 'Mobile Development - Low'), ('MOM', 'Mobile Development - Medium'), ('WDH', 'Web Development - High'), ('WDL', 'Web Development - Low'), ('WDM', 'Web Development - Medium')], default='ITM', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='location',
            field=models.CharField(choices=[('KsmH', 'Kisumu - High'), ('KsmL', 'Kisumu - Low'), ('KsmM', 'Kisumu - Medium'), ('MbsH', 'Mombasa - High'), ('MbsL', 'Mombasa - Low'), ('MbsM', 'Mombasa - Medium'), ('NkuH', 'Nakuru - High'), ('NkuL', 'Nakuru - Low'), ('NkuM', 'Nakuru - Medium'), ('NrbH', 'Nairobi - High'), ('NrbL', 'Nairobi - Low'), ('NrbM', 'Nairobi - Medium'), ('NyrH', 'Nyeri - High'), ('NyrL', 'Nyeri - Low'), ('NyrM', 'Nyeri - Medium'), ('ThkH', 'Thika - High'), ('ThkL', 'Thika - Low'), ('ThkM', 'Thika - Medium')], default='NrbH', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='jobprofile',
            unique_together=set([('title', 'owner')]),
        ),
    ]
